// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BPUNYKl3JzJxT2SQBQkQ8b3ioWhHsoc',
    appId: '1:154419208249:web:dd77a0f06873a0a0e5ede8',
    messagingSenderId: '154419208249',
    projectId: 'fureverhealthy-admin',
    authDomain: 'fureverhealthy-admin.firebaseapp.com',
    storageBucket: 'fureverhealthy-admin.firebasestorage.app',
    measurementId: 'G-L4N3KBHRMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ-gjaPBNHwfG7yXdxeIB5OR0OjWo2wvs',
    appId: '1:154419208249:android:15ba865b63b95606e5ede8',
    messagingSenderId: '154419208249',
    projectId: 'fureverhealthy-admin',
    storageBucket: 'fureverhealthy-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlGLxR3vmlLkhLEX5IGlVG7v7ieaAU4QU',
    appId: '1:154419208249:ios:c1b2eb065b45191be5ede8',
    messagingSenderId: '154419208249',
    projectId: 'fureverhealthy-admin',
    storageBucket: 'fureverhealthy-admin.firebasestorage.app',
    iosClientId: '154419208249-dcll3sb6ro9a2kclj96i8vijesfdd7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fureverhealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlGLxR3vmlLkhLEX5IGlVG7v7ieaAU4QU',
    appId: '1:154419208249:ios:c1b2eb065b45191be5ede8',
    messagingSenderId: '154419208249',
    projectId: 'fureverhealthy-admin',
    storageBucket: 'fureverhealthy-admin.firebasestorage.app',
    iosClientId: '154419208249-dcll3sb6ro9a2kclj96i8vijesfdd7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fureverhealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0BPUNYKl3JzJxT2SQBQkQ8b3ioWhHsoc',
    appId: '1:154419208249:web:8af02cc383ac9615e5ede8',
    messagingSenderId: '154419208249',
    projectId: 'fureverhealthy-admin',
    authDomain: 'fureverhealthy-admin.firebaseapp.com',
    storageBucket: 'fureverhealthy-admin.firebasestorage.app',
    measurementId: 'G-5JJK2ZD7QG',
  );
}
