// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvys5BoKUALqx_DCqPeLlzkNo4MFXjms',
    appId: '1:802623602942:web:056dcfe37c4d5024dfe5af',
    messagingSenderId: '802623602942',
    projectId: 'furever-healthy-2a1ae',
    authDomain: 'furever-healthy-2a1ae.firebaseapp.com',
    storageBucket: 'furever-healthy-2a1ae.firebasestorage.app',
    measurementId: 'G-X2KP2Q18CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq_QtR3ZwaRLjd3p4MXze0cPnRx7k5jco',
    appId: '1:802623602942:android:52edf733baa96c1cdfe5af',
    messagingSenderId: '802623602942',
    projectId: 'furever-healthy-2a1ae',
    storageBucket: 'furever-healthy-2a1ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3dysHYf1bXst4GiS5PeWcsYflv31eXDk',
    appId: '1:802623602942:ios:5cf93d4f8dc9016edfe5af',
    messagingSenderId: '802623602942',
    projectId: 'furever-healthy-2a1ae',
    storageBucket: 'furever-healthy-2a1ae.firebasestorage.app',
    iosBundleId: 'com.example.fureverhealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3dysHYf1bXst4GiS5PeWcsYflv31eXDk',
    appId: '1:802623602942:ios:5cf93d4f8dc9016edfe5af',
    messagingSenderId: '802623602942',
    projectId: 'furever-healthy-2a1ae',
    storageBucket: 'furever-healthy-2a1ae.firebasestorage.app',
    iosBundleId: 'com.example.fureverhealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgvys5BoKUALqx_DCqPeLlzkNo4MFXjms',
    appId: '1:802623602942:web:056dcfe37c4d5024dfe5af',
    messagingSenderId: '802623602942',
    projectId: 'furever-healthy-2a1ae',
    authDomain: 'furever-healthy-2a1ae.firebaseapp.com',
    storageBucket: 'furever-healthy-2a1ae.firebasestorage.app',
    measurementId: 'G-X2KP2Q18CP',
  );

}